seabackend.endpoint: "http://sa-bonn.ddnss.de:3000"
seabackend.defaultTimeout: 10
seabackend.defaultCacheTTL: 10
api.workerCount: 3
flamingo:
  healthcheck:
    checkPath: "/health/check"
    pingPath: "/health/ping"
    checkSession: false
    checkAuth: false
  session:
    backend: memory