package posts

import "encoding/json"

// Generated by https://mholt.github.io/json-to-go/
// Variables need to be UpperCase to be maintained by json marshaller
// json.number allows ids as string and integers
type RemotePost struct {
	UserID json.Number `json:"userId"`
	ID     json.Number `json:"id"`
	Title  string      `json:"title,omitempty"`
	Body   string      `json:"body,omitempty"`
	Text   string      `json:"text,omitempty"`
}
