// Code generated by mockery v2.0.3. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/mkrill/gosea/src/seabackend/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// PostsWithUsersLoader is an autogenerated mock type for the PostsWithUsersLoader type
type PostsWithUsersLoader struct {
	mock.Mock
}

// RetrievePostsWithUsersFromBackend provides a mock function with given fields: ctx, filter
func (_m *PostsWithUsersLoader) RetrievePostsWithUsersFromBackend(ctx context.Context, filter string) ([]entity.Post, error) {
	ret := _m.Called(ctx, filter)

	var r0 []entity.Post
	if rf, ok := ret.Get(0).(func(context.Context, string) []entity.Post); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Post)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
